package Model;
// Generated 10-05-2018 12:26:14 by Hibernate Tools 4.3.1



/**
 * Producto generated by hbm2java
 */
public class Producto  implements java.io.Serializable {


     private short codigo;
     private Marca marca;
     private String descripcion;

    public Producto() {
    }

	
    public Producto(short codigo, String descripcion) {
        this.codigo = codigo;
        this.descripcion = descripcion;
    }
    public Producto(short codigo, Marca marca, String descripcion) {
       this.codigo = codigo;
       this.marca = marca;
       this.descripcion = descripcion;
    }
   
    public short getCodigo() {
        return this.codigo;
    }
    
    public void setCodigo(short codigo) {
        this.codigo = codigo;
    }
    public Marca getMarca() {
        return this.marca;
    }
    
    public void setMarca(Marca marca) {
        this.marca = marca;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }




}


