package Model;
// Generated 10-05-2018 12:26:14 by Hibernate Tools 4.3.1
import java.util.HashSet;
import java.util.Set;
/**
 * Marca generated by hbm2java
 */
public class Marca  implements java.io.Serializable {
     private short codigo;
     private String descripcion;
     private Set<Producto> productos = new HashSet<Producto>(0);

    public Marca() {
    }
	
    public Marca(short codigo) {
        this.codigo = codigo;
    }
    public Marca(short codigo, String descripcion, Set<Producto> productos) {
       this.codigo = codigo;
       this.descripcion = descripcion;
       this.productos = productos;
    }
    public Marca(short codigo, String descripcion) {
       this.codigo = codigo;
       this.descripcion = descripcion;    }
 
    public short getCodigo() {
        return this.codigo;
    }
    
    public void setCodigo(short codigo) {
        this.codigo = codigo;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public Set<Producto> getProductos() {
        return this.productos;
    }
    
    public void setProductos(Set<Producto> productos) {
        this.productos = productos;
    }
}


