package Model;
// Generated 10-05-2018 12:26:14 by Hibernate Tools 4.3.1



/**
 * Usuario generated by hbm2java
 */
public class Usuario  implements java.io.Serializable {


     private String usuario;
     private String clave;
     private String nombre;

    public Usuario() {
    }

	
    public Usuario(String usuario) {
        this.usuario = usuario;
    }
    public Usuario(String usuario, String clave, String nombre) {
       this.usuario = usuario;
       this.clave = clave;
       this.nombre = nombre;
    }
   
    public String getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(String usuario) {
        this.usuario = usuario;
    }
    public String getClave() {
        return this.clave;
    }
    
    public void setClave(String clave) {
        this.clave = clave;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }




}


